language: elixir

elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.0

otp_release:
  - 19.3
  - 20.3
  - 21.2

matrix:
  exclude:
    - elixir: 1.8.0
      otp_release: 19.3

dist: trusty

sudo: required

notifications:
  email: false

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake ffmpeg libopencv-dev sox

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
